name: Update Panel Image

on:
  workflow_dispatch:
jobs:
  build_push_panel:
    name: Build and Push Panel Container
    runs-on: ubuntu-latest
    steps:
    - name: Setup repo
      uses: actions/checkout@v2

    - name: Read Version
      id: read_version
      run: |
        echo "::set-output name=version::$(grep -Po "PANEL_VERSION=\K[^ ]+" ./manifest/version.txt)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        images: ghcr.io/${{ github.repository }}/panel
        flavor: |
          latest=auto
        tags: |
          type=raw,value=${{ steps.read_version.outputs.version }}
          type=raw,value=latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./manifest/images/panel
        file: ./manifest/images/panel/Dockerfile
        platforms: linux/amd64
        build-args: VERSION=${{ steps.read_version.outputs.version }}
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
